---
title: Laws.Africa
timezone: Africa/Johannesburg
collections:
  people:
    title: People
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Laws.Africa is transforming access to legislation in Africa.
baseurl: 
url: https://laws.africa
markdown: kramdown
plugins:
- jekyll-feed
defaults:
-
  scope:
    path: ""
    type: "posts"
  values:
    layout: "blog-post"
